# Generated by Django 5.0.2 on 2024-03-08 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0002_lead_converted_to_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='image',
            field=models.FileField(blank=True, upload_to='images/'),
        ),
    ]
